server:
  port: 7070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:template}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
    clean-on-validation-error: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ""

app:
  cors:
    allowed-origins:
      - http://localhost:63342
      - http://localhost:5173
      - http://localhost:8082
  auth:
    sms:
      dev-code: "123456"
    verification:
      dev-code: "123456"
  firebase:
    enabled: false
